version: "3.9"

services:
  swiftproxy:
    image: quiteafancyemerald/swiftproxy:6.9.6
    build: .
    container_name: swiftproxy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      NODE_ENV: production
